### ISSUE TITLE
No usage by users report for some servers

### ISSUE THREAD

**Issue by nwies** [mjtrangoni/flexlm_exporter#8] opened 2018-05-18 03:13 UTC
### Host operating system: output of `uname -a`
Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### flexlm_exporter version: output of `flexlm_exporter --version`
flexlm_exporter, version 0.0.1 (branch: master, revision: df8de569d92350b4cf04e1a79990b07f781cb524)
  build user:       root@localhost.localdomain
  build date:       20180222-17:37:07
  go version:       go1.8.3

### flexlm_exporter command line flags and relevant YAML configuration file information
Command line
/usr/bin/flexlm_exporter --path.lmutil=/usr/bin/lmutil --path.config=/etc/prometheus/flexlm_exporter.yaml

yaml file

FlexLM Licenses to be monitored.
licenses:

##
  - name: abbrcs_Trappes
    license_server: 27000@UFRTR1DT0070021.COMAUGROUP.COM
    monitor_users: True
    monitor_reservations: True
##
#  - name: kukarcs_Castres
#    license_server: 27001@UFRCAS01LMRP010.COMAUGROUP.COM
#    monitor_users: True
#    monitor_reservations: True
##
#  - name: Tecno_Castres
#    license_server: 27006@UFRCAS01LMRP010.COMAUGROUP.COM
#    monitor_users: True
#    monitor_reservations: True
##
  - name: Xelec_Castres
    license_server: 18000@UFRCAS01LMRP010.COMAUGROUP.COM
    monitor_users: True
    monitor_reservations: True
##
  - name: PS_Castres
    license_server: 28000@UFRCAS01LMRP020.COMAUGROUP.COM
    monitor_users: True
    monitor_reservations: True
##
  - name: PS_Trappes
    license_server: 28000@UFRTRP01LMRP060.COMAUGROUP.COM
    monitor_users: True
    monitor_reservations: True
##
  - name: kuka_Trappes
    license_server: 27001@UFRTRP01LMRP060.COMAUGROUP.COM
    monitor_users: True
    monitor_reservations: True

prometheus.yaml flex_lm part

job_name: 'flexlm'
scrape_interval: '15s'
static_configs:
targets: ['localhost:9319']

### Are you running flexlm_exporter in Docker?
No on a VM 
### What did you do that produced an error?
the metric "flexlm_feature_used_users" is empty for some servers
the metric "flexlm_feature_used" is ok for all the servers
### What did you expect to see?
the full list of users
### What did you see instead?
nothing

### Possible cause:
1)  The servers reporting correctly the used users list 

lmstat -c output:

License server status: 27001@UFRTRP01LMRP060.COMAUGROUP.COM
    License file(s) on UFRTRP01LMRP060.COMAUGROUP.COM: C:\kuka_rcs\COMAU FRANCE_00155DBB9E8B_6955.lic:

UFRTRP01LMRP060.COMAUGROUP.COM: license server UP v11.13.1

Vendor daemon status (on Ufrtrp01lmrp060):

   KUKAROB: UP v9.2

lmstat -a output :
Users of KUKAROB_RCS_8:  (Total of 2 licenses issued;  Total of 1 license in use)

  "KUKAROB_RCS_8" v5.0, vendor: KUKAROB, expiry: 18-may-2019
  nodelocked license locked to NOTHING (hostid=ANY)

    cmfy211 UFRTR1LT0087375 UFRTR1LT0087375 (v2.0) (UFRTRP01LMRP060.COMAUGROUP.COM/27001 101), start Fri 5/18 2:46

2)  The servers NOT  reporting the used users list 

lmstat -c output:
License server status: 28000@UFRTRP01LMRP060.COMAUGROUP.COM
    License file(s) on UFRTRP01LMRP060.COMAUGROUP.COM: C:\Program Files\Siemens\PLMLicenseServer\License_Ugslmd.lic:

UFRTRP01LMRP060.COMAUGROUP.COM: license server UP v11.13.1

Vendor daemon status (on UFRTRP01LMRP060):

    ugslmd: UP v11.13.1

lmstat -a output :
Users of prd_em_workplace_nt:  (Total of 8 licenses issued;  Total of 1 license in use)

  "prd_em_workplace_nt" v14.0, vendor: ugslmd, expiry: permanent(no expiration date)
  floating license

    cmfy211 UFRTR1LT0087375 UFRTR1LT00873750.0 (v12.0) (UFRTRP01LMRP060.COMAUGROUP.COM/28000 101), start Fri 5/18 2:00

there is a ".0" append to the second client computer name on the second server type. Could it be the problem?

Thanks for your feedback.

BR

**Comment by mjtrangoni** [comment] 2018-05-26 17:43
@nwies Thanks for reporting! This should be fixed now. Please tell me if it works as intended.

**Comment by nwies** [comment] 2018-05-28 12:26
hello, I still ahve the problem. PLease find a complete lmstat -a from the server .
[lmstat_trp_pb_a.txt](https://github.com/mjtrangoni/flexlm_exporter/files/2045034/lmstat_trp_pb_a.txt)
[lmstat_trp_pb.txt](https://github.com/mjtrangoni/flexlm_exporter/files/2045035/lmstat_trp_pb.txt)

thanks for our help.

**Comment by nwies** [comment] 2018-05-31 16:54
hello, I compare a working output to the not working .
there is some datas after on the example below : "(linger: 1140944 / 1340160)"

    cmfy211 UFRTR1LT0087375 UFRTR1LT00873750.0 (v1.00) (UFRTRP01LMRP060.COMAUGROUP.COM/28000 1401), start Tue 5/29 9:30  (linger: 1140944 / 1340160)

hope it's help.

BR

**Closed** 2018-05-31 18:01 UTC

**Comment by mjtrangoni** [comment] 2018-05-31 18:03
@nwies yes, you are right. I added support for this now. Could you please check if this work as intended now? Thanks!

**Comment by nwies** [comment] 2018-06-01 15:55
hello,

I just let it run for the day and the lic user name was correctly reported.

thanks for your support.

Br
Nicolas

Le jeu. 31 mai 2018 20:03, Mario Trangoni <notifications@github.com> a
écrit :
